apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pod-delete-experiment
  namespace: litmus
spec:
  # Set to "true" to run the experiment
  engineState: 'active'
  # Choose the ChaosExperiment to run
  # You may need to verify that this experiment is installed in your Litmus setup
  experiment:
    name: pod-delete
  appinfo:
    appns: fastapichaos                 # Namespace where your target application is running
    applabel: 'app=fastapi' # Label of the target application
    appkind: 'deployment'          # Type of target resource (e.g., deployment, statefulset)
  chaosServiceAccount: pod-delete-sa # Service account with permissions for the experiment
  monitoring: false                 # Set to true if you want Prometheus monitoring
  annotationCheck: 'false'          # Set to 'true' if you want to check app annotations for chaos
  jobCleanUpPolicy: 'retain'        # Can be 'delete' or 'retain' based on your preference
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # Define parameters for the experiment
            - name: TARGET_PODS
              value: 'fastapi-deployment-6bb4557bc8-cs75g'   # Name of the specific pod to target
            - name: TOTAL_CHAOS_DURATION
              value: '60'                     # Duration (in seconds) of the chaos experiment
            - name: CHAOS_INTERVAL
              value: '10'                     # Interval (in seconds) between pod deletions
            - name: FORCE
              value: 'false'                  # Use 'true' to force delete without grace period
