apiVersion: v1
kind: Pod
metadata:
  name: proxy-test
spec:
  containers:
  - name: proxy-test
    image: busybox
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do sleep 3600; done"
    env:
      - name: HTTP_PROXY
        value: "http://127.0.0.1:3128"
      - name: HTTPS_PROXY
        value: "http://127.0.0.1:3128"
      - name: NO_PROXY
        value: "localhost,127.0.0.1,.svc,.cluster.local"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
