apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: litmus
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80  # Port on the cluster
      targetPort: 8010  # Port in the container
  type: LoadBalancer
